language: node_js
node_js:
  - "9"

os:
  - linux
  - osx

cache:
  directories:
    - node_modules

before_install: # switch to python 3.6
  - if [ "$TRAVIS_OS_NAME" == 'linux' ];  then source ~/virtualenv/python3.6/bin/activate; fi
  - if [ "$TRAVIS_OS_NAME" == 'linux' ];  then sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ];  then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ];  then brew install python3; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ];  then brew install cairo pango libpng; fi

script:
  - echo $TRAVIS_OS_NAME
  - python3 --version
  - node --version
  - npm --version
  - npm install facenet numjs flash-store # install peer dependencies
  - npm run test
  - npm run test:pack && echo 'Npm packing test is passed'

notifications:
  email:
    on_success: change
    on_failure: change

before_deploy:
  - npm version
  - npm run dist

deploy:
  provider: npm
  email: zixia@zixia.net
  api_key: "$NPM_TOKEN"
  skip_cleanup: true

